Commented 'self.canvas.r' line in open_folder function of nn_gui.1.2.py script
That line was causing an AttributeError with ''Canvas' object has no attribute 'r'' message